### ISSUE TITLE
项目开源协议侵权

### ISSUE THREAD

**Issue by AnzhiZhang** [Aimerny/QQChatPlus#1]
你的项目基于 [QQChat](https://github.com/AnzhiZhang/MCDReforgedPlugins/blob/master/qq_chat/qq_chat/__init__.py) 二次开发，但未遵守 GPL 3.0 协议规定，如不修改我会申请 DMCA takedown

PS：我计划将你的改进版更新到 QQChat 上，如有兴趣可以给你该仓库权限

**Comment by Aimerny** [comment]
可
